stages:
  - build
  - package
  
maven-build:
  image: maven:3.9.0-eclipse-temurin-19
  stage: build
  tags:
    - docker
  script:
    - mvn package -B -s ./.m2/settings.xml
  artifacts:
    untracked: false
    when: on_success
    expire_in: 1 hours
    paths:
      - "target/*-with-dependencies.jar"

docker-build:
  stage: package
  tags:
    - shell
  script:
    - docker build -t oldhook/alert_telebot .
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker push oldhook/alert_telebot
    - docker logout
    - docker system prune --all --volumes --force